version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/music-service-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    container_name: music-service-db
    image: 'postgres:13.1-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=music-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  minio:
    image: bitnami/minio:2023.4.28
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminqwerty
    volumes:
      - minio-data:/data
    ports:
      - 9900:9000
      - 9901:9001

volumes:
  minio-data:
