minio:
  access-key: s54FEu7WmkuXoL3f
  secret-key: HlFR1FcMybUlFe8jDqob5mCPxit4X9JZ
  bucket: music-service-bucket
  url: http://minio:9000

spring:
  datasource:
    url: ${spring_datasource_url:jdbc:postgresql://postgres:5432/music-service-db}
    username: ${spring_datasource_username:postgres}
    password: ${spring_datasource_password:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${spring_jpa_hibernate_ddl-auto:update}
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  servlet:
    multipart:
      max-file-size: 10MB

jwt-token:
  permit-all:
    - /api/users/register
    - /api/users/login
  root-path: /api
  secret: qqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrttty
  issuer: music-service-api
  subject: User details